"""Add cv_filename to Application model

Revision ID: 1e74a3716e89
Revises: 983c2fd8ed3e
Create Date: 2024-10-13 13:28:16.463811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e74a3716e89'
down_revision = '983c2fd8ed3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('cv_filename')

    # ### end Alembic commands ###
