"""CV TEXT

Revision ID: b84613fcf360
Revises: 1e74a3716e89
Create Date: 2024-10-13 16:09:20.625677

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b84613fcf360'
down_revision = '1e74a3716e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_text', sa.Text(), nullable=True))
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint('application_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'job', ['job_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('cv_filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cv_filename', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('application_ibfk_2', 'job', ['job_id'], ['id'])
        batch_op.alter_column('job_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.drop_column('cv_text')

    # ### end Alembic commands ###
